#!/usr/bin/python
# -*- coding: utf-8 -*-

import os
import sys
import shutil
import logging

import aeios

"""
Tool to configure aeios
"""

__author__ = 'Sam Forester'
__email__ = 'sam.forester@utah.edu'
__copyright__ = 'Copyright (c) 2019 University of Utah, Marriott Library'
__license__ = 'MIT'
__version__ = "1.1.0"

# name of this script
SCRIPT = os.path.basename(sys.argv[0])

def add(resources, args):
    logger = logging.getLogger(__name__)

    #> aeiosutil add wifi PATH
    if args.item == 'wifi':
        aeios.utility.add_wifi_profile(args.path, resources.wifi)

    #> aeiosutil add image (--lock | --alert | --background) PATH
    elif args.item == 'image':
        aeios.utility.add_item(args.path, resources.images, name=args.image)
        logger.info("added %s image: %s", args.image, args.path)

    #> aeiosutil add identity (--p12 | --certs) PATH
    elif args.item == 'identity':
        try:
            if args.p12:
                #> aeiosutil add identity --p12 PATH
                aeios.utility.add_p12(args.path, resources.supervision)
                logger.info("converted p12: %r", args.path)
            else:
                #> aeiosutil add identity --certs PATH
                aeios.utility.copy_certs(args.path)
                logger.info("imported identity files: %r", args.path)
        except ValueError as e:
            # both copy_certs() and add_p12() raise ValueErrors
            raise SystemExit("{0!s}: {1!s}".format(SCRIPT, e))

    #> aeiosutil add app "app name"
    elif args.item == 'app':
        if not args.name:
            raise SystemExit("must specify app name")
        logger.debug(u"adding app: '%s'", args.name)
        manager = aeios.apps.AppManager().add('all-iPads', args.name)
        logger.info(u"added app to automation: '%s'", args.name)
    else:
        err = "{0!s}: unable to add {1!r}".format(SCRIPT, args.item)
        raise SystemExit(err)


def remove(resources, args):
    logger = logging.getLogger(__name__)

    #> aeiosutil remove wifi
    if args.item == 'wifi':
        logger.debug("> remove: %r", resources.wifi)
        try:
            os.remove(resources.wifi)
        except OSError as e:
            if e.errno == 2:
                # profile is already removed
                pass
        logger.info("successfully removed Wi-Fi profile")

    #> aeiosutil remove image (--background | --lock | --alert | --all)
    elif args.item == 'image':
        if args.image == 'all':
            logger.debug("> rmtree: %r", resources.images)
            shutil.rmtree(resources.images)
            logger.debug("> mkdir: %r", resources.images)
            os.mkdir(resources.images)
            logger.info("all images removed")
        else:
            images = os.listdir(resources.images)
            logger.debug("images: %r", images)
            try:
                name = [x for x in images if x.startswith(args.image)][0]
                path = os.path.join(resources.images, name)
                logger.debug("> remove: %r", path)
                os.remove(path)
            except IndexError:
                pass
            logger.info("%s image removed", args.image)

    #> aeiosutil remove identity
    elif args.item == 'identity':
        logger.debug("> remove: %r", resources.key)
        os.remove(resources.key)
        logger.debug("> remove: %r", resources.cert)
        os.remove(resources.cert)
        logger.info("removed supervision identity")

    #> aeiosutil remove app "app name"
    elif args.item == 'app':
        logger.debug(u"removing: '%s'", args.name)
        manager = aeios.apps.AppManager().remove(args.name)
        logger.info(u"removed app from automation: '%s'", args.name)

    #> aeiosutil remove reporting
    elif args.item == 'reporting':
        resources.reporting(aeios.resources.DEFAULT.reporting)
        logger.info("removed reporting configuration")
    else:
        err = "{0!s}: unable to remove {1!r}".format(SCRIPT, args.item)
        raise SystemExit(err)


def configure(resources, args):
    logger = logging.getLogger(__name__)

    #> aeiosutil configure slack URL CHANNEL [--name NAME]
    if args.item == 'slack':
        data = {'URL': args.URL, 'channel': args.channel, 'name': args.name}
        resources.reporting({'Slack': data})
        logger.info("successfully configured reporting")
    else:
        err = "{0!s}: unable to configure {1!r}".format(SCRIPT, args.item)
        raise SystemExit(err)


def main(argv):
    logger = logging.getLogger(__name__)
    
    # NOTE: defining before logging.basicConfig suppresses logging
    resources = aeios.resources.Resources()

    parser = aeios.utility.Parser()
    args = parser.parse(argv)

    if args.version:
        raise SystemExit("{0}: v{1}".format(SCRIPT, __version__))

    # there's probably a better way to dynamically format logging...
    format = '{0!s}: %(message)s'.format(SCRIPT)
    if args.debug:
        format = ('%(asctime)s %(levelname)6s: %(name)s - %(funcName)s(): '
                  '%(message)s')
        level = logging.DEBUG
    elif args.verbose:
        level = logging.INFO
    else:
        level = logging.CRITICAL

    logging.basicConfig(format=format, level=level)

    if args.cmd == 'add':
        # resources.add()
        add(resources, args)
    elif args.cmd == 'remove':
        remove(resources, args)
    elif args.cmd == 'configure':
        configure(resources, args)
    elif args.cmd == 'start':
        aeios.utility.start(args.login)
    elif args.cmd == 'stop':
        aeios.utility.stop(args.login)


if __name__ == '__main__':
    main(sys.argv[1:])
